---
{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "compreface.hardcodedValues"  -}}

additionalContainers:
  api:
    name: compreface-api
    image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
    imagePullPolicy: "{{ .Values.api.image.pullPolicy }}"
    env:
      - name: API_JAVA_OPTS
        value: '-Xmx8g'
      - name: POSTGRES_PASSWORD
        value: '{{ .Values.postgres.auth.password }}'
      - name: POSTGRES_URL
        value: 'jdbc:postgresql://{{ .Values.postgres.fullnameOverride }}:5432/{{ .Values.postgres.auth.database }}'
      - name: POSTGRES_USER
        value: '{{ .Values.postgres.auth.username }}'
      - name: SAVE_IMAGES_TO_DB
        value: 'true'
      - name: SPRING_PROFILES_ACTIVE
        value: 'dev'
      {{- range $name, $value := .Values.api.env }}
      - name: {{ $name }}
        value: {{ $value | quote }}
      {{- end }}
    ports:
      - name: api
        containerPort: {{.Values.api.port}}

  admin:
    name: compreface-admin
    image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
    imagePullPolicy: "{{ .Values.admin.image.pullPolicy }}"
    env:
      - name: ADMIN_JAVA_OPTS
        value: '-Xmx8g'
      - name: EMAIL_FROM
      - name: EMAIL_HOST
      - name: EMAIL_PASSWORD
      - name: EMAIL_USERNAME
      - name: ENABLE_EMAIL_SERVER
      - name: POSTGRES_PASSWORD
        value: '{{ .Values.postgres.auth.password }}'
      - name: POSTGRES_URL
        value: 'jdbc:postgresql://{{ .Values.postgres.fullnameOverride }}:5432/{{ .Values.postgres.auth.database }}'
      - name: POSTGRES_USER
        value: '{{ .Values.postgres.auth.username }}'
      - name: SAVE_IMAGES_TO_DB
        value: 'true'
      - name: SPRING_PROFILES_ACTIVE
        value: 'dev'
      {{- range $name, $value := .Values.api.env }}
      - name: {{ $name }}
        value: {{ $value | quote }}
      {{- end }}
    ports:
      - name: admin
        containerPort: {{.Values.admin.port}}

  fe:
    name: compreface-ui
    image: "{{ .Values.fe.image.repository }}:{{ .Values.fe.image.tag }}"
    imagePullPolicy: "{{ .Values.fe.image.pullPolicy }}"
    env:
      - name: ADMIN_JAVA_OPTS
        value: '-Xmx8g'
      - name: EMAIL_FROM
      - name: EMAIL_HOST
      - name: EMAIL_PASSWORD
      - name: EMAIL_USERNAME
      - name: ENABLE_EMAIL_SERVER
      - name: POSTGRES_PASSWORD
        value: '{{ .Values.postgres.auth.password }}'
      - name: POSTGRES_URL
        value: 'jdbc:postgresql://{{ .Values.postgres.fullnameOverride }}:5432/{{ .Values.postgres.auth.database }}'
      - name: POSTGRES_USER
        value: '{{ .Values.postgres.auth.username }}'
      - name: SAVE_IMAGES_TO_DB
        value: 'true'
      - name: SPRING_PROFILES_ACTIVE
        value: 'dev'
      {{- range $name, $value := .Values.api.env }}
      - name: {{ $name }}
        value: {{ $value | quote }}
      {{- end }}
    ports:
      - name: ui
        containerPort: {{.Values.fe.port}}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "compreface.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}