# Default values for compreface-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

config:
  #image backup
  save_image_to_db: true
  #email config
  email_host: "smtp.gmail.com"
  email_username:
  email_from:
  email_password:
  enable_email_server: false
  #max size and timout settings
  max_file_size: "5MB"
  max_request_size: "10MB"
  connection_timeout: 10000
  read_timeout: 60000

postgres:
  repository: postgres
  pullPolicy: Always
  tag: 11.5
  db_name: frs
  db_port: 5432
  db_password: postgres
  db_user: postgres
  name: compreface-db-data
  db_storage_class: longhorn
  db_storage_size: 100Mi

core:
  repository: exadel/compreface-core
  pullPolicy: Always
  tag: 1.1.0
  port: 3000
  uwsgi_processes: 2
  uwsgi_threads: 1
  replicas: 1
  name: compreface-core

api:
  repository: exadel/compreface-api
  pullPolicy: Always
  tag: 1.1.0
  port: 8080
  replicas: 1
  name: compreface-api
  compreface_java_options: "-Xmx4g"

admin:
  repository: exadel/compreface-admin
  pullPolicy: Always
  tag: 1.1.0
  port: 8080
  replicas: 1
  name: compreface-admin
  compreface_java_options: "-Xmx1g"

fe:
  repository: exadel/compreface-fe
  pullPolicy: Always
  tag: 1.1.0
  port: 80
  replicas: 1
  name: compreface-fe

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "compreface"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
