controller:
  replicas: 1

image:
  repository: rhasspy/wyoming-whisper
  tag: "latest"
  pullPolicy: IfNotPresent
  args: ["--model", "tiny-int8", "--language en"]

service:
  main:
    enabled: true
    type: ClusterIP

    ports:
      http:
        enabled: true
        primary: true
        protocol: TCP
        port: 10300
     
ingress:
  main:
    enabled: false

persistence:
  data:
    enabled: false
    type: pvc
    mountPath: /data
    storageClass:  # "-"
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: false



