---
apiVersion: v2
description: The easiest way to run WireGuard VPN + Web-based Admin UI.
name: wg-easy
version: 0.0.1
maintainers:
  - name: AntorFR
    email: contact@antor.fr
dependencies:
  - name: common
    repository: https://antorfr.github.io/smart-home-charts
    version: 4.5.8
sources:
  - https://github.com/WeeJeWel/wg-easy
  - https://ghcr.io/wg-easy/wg-easy
type: application
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: First chart release
