---
apiVersion: v2
description: TasmoAdmin is an administrative platform for devices flashed with Tasmota.
name: tasmoadmin
version: 0.0.1
maintainers:
  - name: AntorFR
    email: contact@antor.fr
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: First chart release
