controller:
  replicas: 1
  strategy: RollingUpdate
  rollingUpdate:
    unavailable: 0
    surge: 1

image:
  repository: platerecognizer/alpr
  tag: "latest"
  pullPolicy: Always

secret:
  TOKEN: your-token
  LICENSE_KEY: your-license-key

env:
  TZ: UTC

envFrom: 
 - secretRef: TOKEN
   name: platerec
 - secretRef: LICENSE_KEY
   name: platerec

service:
  main:
    enabled: true
    type: ClusterIP
    externalTrafficPolicy: Cluster

    ports:
      http:
        enabled: true
        port: 8080
      http-live:
        enabled: true
        protocol: TCP
        port: 8081        

ingress:
  main:
    enabled: false

persistence:
  license:
    enabled: false
    type: pvc
    mountPath: /license
    storageClass:  # "-"
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: false


probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /liveliness/
        port: http-live
      initialDelaySeconds: 15
      timeoutSeconds: 60
  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /readiness/
        port: http-live
      initialDelaySeconds: 15
      timeoutSeconds: 60
