#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: jupyter/base-notebook
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [teamspeak image documentation](https://hub.docker.com/_/teamspeak).
# @default -- See below
env:
  #NB_UID: "{{ .Values.securityContext.container.PUID }}"
  #NB_GID: "{{ .Values.securityContext.pod.fsGroup }}"
  #NB_UMASK: "{{ .Values.securityContext.container.UMASK }}"
  # User Defined
  DOCKER_STACKS_JUPYTER_CMD: 'lab'
  RESTARTABLE: 'yes'


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 10300
        targetPort: 8888

persistence:
  data:
    enabled: false
    type: pvc
    mountPath: /home/jovyan/work
    storageClass:  # "-"
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false


