controller:
  replicas: 1

image:
  repository: mitmproxy/mitmproxy
  tag: "latest"
  pullPolicy: Always

args:
  - mitmweb
  - --web-host
  - 0.0.0.0

env:
  TZ: UTC

service:
  main:
    enabled: true
    type: ClusterIP

    ports:
      http:
        enabled: false
        primary: false
      proxy:
        primary: true
        enabled: true
        protocol: TCP
        port: 8080
      web:
        enabled: true
        protocol: TCP
        port: 8081        

ingress:
  main:
    enabled: false

persistence:
  logs:
    enabled: false
    type: pvc
    mountPath: /logs
    storageClass:  # "-"
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: false



