{{/* Create the .env file Secret for nestor-mcp */}}
{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-env
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |
{{ required "envFile.content must be set" .Values.envFile.content | indent 4 }}
