controller:
  replicas: 1

image:
  repository: "ghcr.io/antorfr/wyoming-porcupine3/amd64"
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  TZ: UTC
  SENSITIVITY: 0.5
  ACCESS_KEY: "ACCESS_KEY"

service:
  main:
    enabled: true
    type: ClusterIP

    ports:
      http:
        enabled: true
        primary: true
        protocol: TCP
        port: 10400
     
ingress:
  main:
    enabled: false

persistence:
  data:
    enabled: false
    type: pvc
    mountPath: /usr/src/data/resources
    storageClass:  # "-"
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: false



