---
apiVersion: v2
description: The chart will run a Minecraft Bedrock Dedicated Server (MBDS)
name: minecraft-server
version: 0.0.4
maintainers:
  - name: AntorFR
    email: contact@antor.fr
dependencies:
  - name: common
    repository: https://antorfr.github.io/smart-home-charts
    version: 4.5.8
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: First chart release
