---
apiVersion: v2
description: The chart will run a Minecraft Bedrock Dedicated Server (MBDS)
name: minecraft-server
version: 0.1.3
maintainers:
  - name: AntorFR
    email: contact@antor.fr
dependencies:
  - name: common
    repository: https://antorfr.github.io/smart-home-charts
    version: 4.5.8
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.30
    condition: mapViz.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: First chart release
