#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  type: statefulset
  replicas: 1

image:
  # -- image repository
  repository: itzg/minecraft-bedrock-server
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [teamspeak image documentation](https://hub.docker.com/_/teamspeak).
# @default -- See below
env:
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
        primary: false
      udp:
        enabled: true
        primary: true
        port: 19132
        protocol: UDP

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["mc-monitor", "status-bedrock", "--host", "127.0.0.1"]
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["mc-monitor", "status-bedrock", "--host", "127.0.0.1"]
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

  startup:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["mc-monitor", "status-bedrock", "--host", "127.0.0.1"]
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/arch"
            operator: In
            values:
              - amd64

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false


persistence:
  worlds:
    enabled: false
    type: pvc
    mountPath:  /data/worlds
    readOnly: false
    nameOverride:
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false

  # -- Create an emptyDir volume to share between all containers
  # [[ref]]https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)
  # @default -- See below
  data:
    enabled: true
    type: emptyDir
    mountPath: /data