#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  type: deployment
  replicas: 1

image:
  # -- image repository
  repository: itzg/minecraft-bedrock-server
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [teamspeak image documentation](https://hub.docker.com/_/teamspeak).
# @default -- See below
env:
  TZ: UTC

  # Find more options at https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
  # Remove # from in front of line if changing from default values.
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  #GAMEMODE: "survival" # Options: survival, creative, adventure
  #DIFFICULTY: "easy" # Options: peaceful, easy, normal, hard
  #DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
  #LEVEL_NAME: "my_minecraft_world"
  #LEVEL_SEED: "33480944"
  #SERVER_NAME: "my_minecraft_server"
  SERVER_PORT: "19132"
  #LEVEL_TYPE: "DEFAULT" # Options: FLAT, LEGACY, DEFAULT
  #ALLOW_CHEATS: "false" # Options: true, false
  #MAX_PLAYERS: "10"
  #PLAYER_IDLE_TIMEOUT: "30"
  #TEXTUREPACK_REQUIRED: "false" # Options: true, false
  #
  ## Changing these will have a security impact
  #ONLINE_MODE: "true" # Options: true, false (removes Xbox Live account requirements)
  #WHITE_LIST: "false" # If enabled, need to provide a whitelist.json by your own means. 
  #
  ## Changing these will have a performance impact
  #VIEW_DISTANCE: "10"
  #TICK_DISTANCE: "4"
  #MAX_THREADS: "8"


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
        primary: false
      udp:
        enabled: true
        primary: true
        port: 19132
        protocol: UDP

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["mc-monitor", "status-bedrock", "--host", "127.0.0.1"]
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["mc-monitor", "status-bedrock", "--host", "127.0.0.1"]
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

  startup:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["mc-monitor", "status-bedrock", "--host", "127.0.0.1"]
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 30

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/arch"
            operator: In
            values:
              - amd64

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

persistence:
  worlds:
    enabled: false
    type: pvc
    mountPath:  /data/worlds
    readOnly: false
    nameOverride:
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false

  data:
    enabled: true
    type: emptyDir
    mountPath: /data

mapViz:
  enabled: false
  persistence:
    vizhtml:
      enabled: false
      type: pvc
      mountPath:  '-'
      accessMode: ReadWriteMany
      size: 100Mi

  ingress:
    mapviz:
      enabled: false
      
  schedule: "0 3 * * *"
  image:
    # -- image used for map export
    repository: oberard/bedrock-viz:1.0.0
    # -- image pull policy
    pullPolicy: IfNotPresent
    # -- image pull tag
    tag: latest

  env:
  command:
  restartPolicy: Never

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/arch"
              operator: In
              values:
                - amd64

  resources:
    requests:
      # -- requested memory for map html export
      memory: "50Mi"
      # -- requested cpu for map html export
      cpu: "5m"

nginx:
  staticSitePVC: minecraft-server-vizhtml
  ingress.enabled: false

 