env:
  TZ: Europe/Paris
  VERSION: "1.19.70.02"
  # Find more options at https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
  GAMEMODE: "survival" # Options: survival, creative, adventure
  DIFFICULTY: "easy" # Options: peaceful, easy, normal, hard
  DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
  LEVEL_NAME: "p57qYwgNMwA="
  #LEVEL_SEED: ""
  SERVER_NAME: "Berard Server"
  SERVER_PORT: "19132"
  #LEVEL_TYPE: "DEFAULT" # Options: FLAT, LEGACY, DEFAULT
  #ALLOW_CHEATS: "false" # Options: true, false
  MAX_PLAYERS: "5"
  #PLAYER_IDLE_TIMEOUT: "30"
  #TEXTUREPACK_REQUIRED: "false" # Options: true, false
  
  ## Changing these will have a security impact
  ONLINE_MODE: "false" # Options: true, false (removes Xbox Live account requirements)
  #WHITE_LIST: "false" # If enabled, need to provide a whitelist.json by your own means. 
  
  ## Changing these will have a performance impact
  #VIEW_DISTANCE: "10"
  #TICK_DISTANCE: "4"
  #MAX_THREADS: "8"
  OPS: "2535436004579493"

ingress:
  main:
    enabled: true
    hosts:
      - host: "minecradt.k3s.intra.sberard.fr"
        paths:
        - path: /
          pathType: Prefix
          service:
            name: minecraft-server

persistence:
  worlds:
    enabled: true
    storageClass: longhorn
    type: pvc
    size: 1Gi
    retain: false

addons:
  codeserver:
    enabled: true
    image:
      repository: codercom/code-server
      tag: 4.9.1
    args:
      - --auth
      - none
      - --user-data-dir
      - /data/.vscode
      - --extensions-dir
      - "/data/.vscode"
    workingDir: "/data"
    volumeMounts:
    - name: data
      mountPath: /data
    - name: worlds
      mountPath: /data/worlds
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: dev.minecraft.k3s.intra.sberard.fr
        paths:
        - path: /
          pathType: Prefix
          
mapViz:
  enabled: true
  ingress:
    mapViz:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: mapviz.minecraft.k3s.intra.sberard.fr
        paths:
        - path: /
          pathType: Prefix
      
