---
{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "minecraft.harcodedValues" -}}
{{- if .Values.mapViz.enabled -}}

{{- if .Values.mapViz.ingress.mapviz.enabled -}}
{{/* Set port number used by dataViz */}}
{{- $servicename := print (include "common.names.fullname" .) "-nginx" }}
{{- $serviceport := 80 }}

{{- range .Values.mapViz.ingress.mapviz.hosts }}
{{- range .paths }}
{{- $_ := mergeOverwrite . (dict "service" (dict "port" $serviceport "name" $servicename )) -}}
{{- end }}
{{- end }}
{{- end }}

ingress:
{{ .Values.mapViz.ingress | toYaml | nindent 2 }}

persistence:
  worlds:
    accessMode: ReadWriteMany
{{ .Values.mapViz.persistence | toYaml | nindent 2 }}
{{- end }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "minecraft.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
