---
apiVersion: v2
description: SmartIoT-config is an config system for SmartIoT Esp32/Esp8266 firmware helping for discovery, OTA upate and config backup.
name: smartiot-config
version: 0.3.1-alpha.1
maintainers:
  - name: AntorFR
    email: contact@antor.fr
dependencies:
  - name: common
    repository: https://antorfr.github.io/smart-home-charts
    version: 4.5.6-alpha.1
  #- name: common
  #  repository: https://library-charts.k8s-at-home.com
  #  version: 4.5.2
  #- name: common
  #  version: 1.3.1
  #  repository: https://bjw-s.github.io/helm-charts/`
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: First chart release
    - kind: changed
      description: update data persistence with v1.1.0 of the app
    - kind: changed
      description: bump common depedency to v1.3.2