controller:
  replicas: 1

image:
  repository: semaphoreui/semaphore
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  TZ: UTC
  SEMAPHORE_DB_USER: semaphore
  SEMAPHORE_DB_PASS: semaphore
  SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
  SEMAPHORE_DB_PORT: 5432  # change to 3306 for mysql
  SEMAPHORE_DB_DIALECT: postgres  # for mysql, change to: mysql
  SEMAPHORE_DB: semaphore
  SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
  SEMAPHORE_ADMIN_PASSWORD: changeme
  SEMAPHORE_ADMIN_NAME: admin
  SEMAPHORE_ADMIN_EMAIL: admin@localhost
  SEMAPHORE_ADMIN: admin
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
  SEMAPHORE_WEB_HOST: https://exmaple.com/semaphore
  SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes' 
  SEMAPHORE_LDAP_HOST: dc01.local.example.com
  SEMAPHORE_LDAP_PORT: '636'
  SEMAPHORE_LDAP_NEEDTLS: 'yes'
  SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
  SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
  SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
  SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: false
        port: 3000 

ingress:
  main:
    enabled: false

persistence:
  logs:
    enabled: false
    type: pvc
    mountPath: /logs
    storageClass:  # "-"
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: false

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 15.4
  auth:
    postgresPassword: "changeme"
    username: semaphore
    password: semaphore
    database: semaphore
  primary:
    persistence:
      enabled: false
      storageClass: "-"
      size: 1Gi



