apiVersion: v2
name: lldap
description: lldap lightweight is a authentication server that provides an opinionated, simplified LDAP interface for authentication
type: application
version: 0.0.1
appVersion: latest
home: https://github.com/lldap/lldap
sources:
  - https://github.com/lldap/lldap
dependencies:
  - name: common
    repository: https://antorfr.github.io/smart-home-charts
    version: 4.5.8