apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: '{{ .Values.api.repository }}:{{ .Values.api.tag }}'
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: API_JAVA_OPTS
              value: "{{ .Values.api.compreface_java_options }}"
            - name: POSTGRES_PASSWORD
              value: '{{ .Values.postgres.db_password }}'
            - name: POSTGRES_URL
              value: 'jdbc:postgresql://compreface-postgres-db:{{ .Values.postgres.db_port }}/{{ .Values.postgres.db_name }}'
            - name: POSTGRES_USER
              value: '{{ .Values.postgres.db_user }}'
            - name: SAVE_IMAGES_TO_DB
              value: 'true'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            - name: SAVE_IMAGES_TO_DB
              value: "{{ .Values.config.save_image_to_db }}"
            - name: MAX_FILE_SIZE
              value: "{{ .Values.config.max_file_size }}"
            - name: MAX_REQUEST_SIZE
              value: "{{ .Values.config.max_request_size }}B"
            - name: CONNECTION_TIMEOUT
              value: "{{ .Values.config.connection_timeout }}" 
            - name: READ_TIMEOUT
              value: "{{ .Values.config.read_timeout }}"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-api
spec:
  type: ClusterIP
  selector:
      app: api
  ports:
  - port: {{ .Values.api.port }}
