apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin
  name: {{ .Values.admin.name }}
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - env:
            - name: ADMIN_JAVA_OPTS
              value: "{{ .Values.admin.compreface_java_options }}"
            - name: EMAIL_FROM
              value: "{{ .Values.config.email_from }}"
            - name: EMAIL_HOST
              value: "{{ .Values.config.email_host }}"
            - name: EMAIL_PASSWORD
              value: "{{ .Values.config.email_password }}"
            - name: EMAIL_USERNAME
              value: "{{ .Values.config.email_username }}"
            - name: ENABLE_EMAIL_SERVER
              value: "{{ .Values.config.enable_email_server }}"
            - name: POSTGRES_PASSWORD
              value: '{{ .Values.postgres.db_password }}'
            - name: POSTGRES_URL
              value: 'jdbc:postgresql://compreface-postgres-db:{{ .Values.postgres.db_port }}/{{ .Values.postgres.db_name }}'
            - name: POSTGRES_USER
              value: '{{ .Values.postgres.db_user }}'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            - name: MAX_FILE_SIZE
              value: "{{ .Values.config.max_file_size }}"
            - name: MAX_REQUEST_SIZE
              value: "{{ .Values.config.max_request_size}}"              
          image: '{{ .Values.admin.repository }}:{{ .Values.admin.tag }}'
          ports:
          - containerPort: {{ .Values.admin.port }}
          name: {{ .Values.admin.name }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-admin
spec:
  type: ClusterIP
  selector:
      app: admin
  ports:
  - port: {{ .Values.admin.port }}
