apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe
  name: {{ .Values.fe.name }}
spec:
  replicas: {{ .Values.fe.replicas }}
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: {{ .Values.fe.name }}
          image: '{{ .Values.fe.repository }}:{{ .Values.fe.tag }}'
          ports:
            - containerPort: {{ .Values.fe.port }}
          env:
            - name: CLIENT_MAX_BODY_SIZE
              value: "{{ .Values.config.max_request_size }}"
            - name: PROXY_READ_TIMEOUT
              value: {{ .Values.config.connection_timeout }}  
            - name: PROXY_CONNECT_TIMEOUT
              value: {{ .Values.config.read_timeout }}       
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fe
  name: compreface-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.fe.port }}
  selector:
    app: fe
