apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe
  name: {{ .Values.fe.name }}
spec:
  replicas: {{ .Values.fe.replicas }}
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - image: '{{ .Values.fe.repository }}:{{ .Values.fe.tag }}'
          name: {{ .Values.fe.name }}
          ports:
            - containerPort: {{ .Values.fe.port }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fe
  name: compreface-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.fe.port }}
  selector:
    app: fe

{{- if .Values.ingress.enabled }}
{{- $values := .Values.ingress -}}
{{- $port := .Values.service.port -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compreface-ingress
  annotations:
    {{- with $values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- range $values.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ tpl .path $ | quote }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: "compreface-ui"
                port:
                  number: {{ default $port .port }}
        {{- end }}
  {{- end }}
{{- end }}