controller:
  replicas: 1

image:
  repository: ghcr.io/music-assistant/server
  tag: "latest"
  pullPolicy: IfNotPresent

# -- Enable devices to be discoverable
hostNetwork: true
# -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
dnsPolicy: ClusterFirstWithHostNet

service:
  main:
    enabled: true
    type: ClusterIP

    ports:
      http:
        enabled: true
        primary: true
        protocol: TCP
        port: 8095
     
ingress:
  main:
    enabled: false

persistence:
  data:
    enabled: false
    type: pvc
    mountPath: /data
    storageClass:  # "-"
    accessMode: ReadWriteOnce
    size: 100Mi
    retain: false



