---
apiVersion: v2
description: A Helm chart of compreface for Kubernetes
name: compreface2
version: 0.0.6
appVersion: "1.0.1"
type: application
maintainers:
  - name: AntorFR
    email: contact@antor.fr
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: postgresql
    version: 11.6.19
    repository: https://charts.bitnami.com/bitnami
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: First chart release


