---
{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Render secrets for cloudflareddns */}}
{{- $secrets := include "cloudflareddns.secret" . | fromYaml -}}
{{- if $secrets -}}
  {{- $_ := set .Values "secret" $secrets -}}
{{- end -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
