---
{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}


{{/* Render secrets for cloudflareddns */}}
{{- if or .Values.envFrom .Values.secret }}
{{- $secrets := include "cloudflareddns.secret" . | fromYaml -}}
{{- if $secrets -}}
  {{- $_ := set .Values.secret "secret" $secrets -}}
{{- end -}}

{{/* Render the templates */}}
{{ include "common.all" . }}